version: '3.8'

services:
  hardn-test:
    build: .
    container_name: hardn-compliance-test
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: >
      bash -c "
      echo '=== HARDN-XDR Lynis Compliance Test ===';
      echo 'System: Debian 12 (Bookworm)';
      echo 'Testing HARDN installation...';
      /hardn/test-hardn-installation.sh;
      echo '';
      echo '=== Running Baseline Lynis Audit ===';
      lynis audit system --quiet --no-colors --log-file /tmp/baseline.log --report-file /tmp/baseline.dat;
      BASELINE_SCORE=$$(grep 'hardening_index' /tmp/baseline.dat | cut -d'=' -f2 | tr -d ' ' || echo '0');
      echo \"Baseline Hardening Index: $$BASELINE_SCORE%\";
      echo '';
      echo '=== Installing HARDN-XDR ===';
      cd /hardn && timeout 1200 ./src/setup/hardn-main.sh --non-interactive || echo 'HARDN installation completed';
      echo '';
      echo '=== Running Post-HARDN Lynis Audit ===';
      lynis audit system --quiet --no-colors --log-file /tmp/post-hardn.log --report-file /tmp/post-hardn.dat;
      POST_SCORE=$$(grep 'hardening_index' /tmp/post-hardn.dat | cut -d'=' -f2 | tr -d ' ' || echo '0');
      echo \"Post-HARDN Hardening Index: $$POST_SCORE%\";
      echo '';
      echo '=== COMPLIANCE RESULT ===';
      if [ \"$$POST_SCORE\" -ge 90 ]; then
        echo \"PASS: Lynis compliance score is $$POST_SCORE% (>= 90%)\";
        echo \"Improvement: $$((POST_SCORE - BASELINE_SCORE))%\";
      else
        echo \"FAIL: Lynis compliance score is $$POST_SCORE% (< 90%)\";
        echo \"Improvement: $$((POST_SCORE - BASELINE_SCORE))%\";
        exit 1;
      fi;
      sleep 30;
      "

  hardn-dev:
    build: .
    container_name: hardn-development
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - .:/hardn-dev
    working_dir: /hardn-dev
    command: /bin/bash
    stdin_open: true
    tty: true